CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port=12231 --use_env run_train.py \
--diff_steps 2000 \
--lr 0.0001 \
--learning_steps 100000 \
--save_interval 10000 \
--seed 102 \
--noise_schedule sqrt \
--hidden_dim 128 \
--bsz 256 \
--delay_opt 1 \
--microbatch 128 \
--dataset qqp \
--data_dir datasets/QQP \
--learned_mean_embed True \
--denoise True \
--vocab bert \
--seq_len 98 \
--use_fp16 \
--denoise_rate 0.5 \
--schedule_sampler lossaware \
--notes maxlen98_lambda0_triplet_KL \
--_lambda 0.0 \
